/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface GetAnalysisStreamRequest {
  refresh?: boolean;
}

/**
 *
 */
export class AnalysisControllerApi extends runtime.BaseAPI {

  /**
   *
   * get_analysis_stream
   */
  async getAnalysisStreamRaw(requestParameters: GetAnalysisStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
    const queryParameters: any = {};

    if (requestParameters['refresh'] != null) {
      queryParameters['refresh'] = requestParameters['refresh'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request({
      path: `/analysis/stream`,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }, initOverrides);

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   *
   * get_analysis_stream
   */
  async getAnalysisStream(requestParameters: GetAnalysisStreamRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
    const response = await this.getAnalysisStreamRaw(requestParameters, initOverrides);
    return await response.value();
  }

}
