/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 生物特征图表数据DTO
 * @export
 * @interface BiometricChartDataDto
 */
export interface BiometricChartDataDto {
    /**
     * 日期列表
     * @type {Array<string>}
     * @memberof BiometricChartDataDto
     */
    dates?: Array<string>;
    /**
     * 体重列表 (kg)
     * @type {Array<number>}
     * @memberof BiometricChartDataDto
     */
    weights?: Array<number>;
    /**
     * 收缩压列表 (mmHg)
     * @type {Array<number>}
     * @memberof BiometricChartDataDto
     */
    systolicPressures?: Array<number>;
    /**
     * 舒张压列表 (mmHg)
     * @type {Array<number>}
     * @memberof BiometricChartDataDto
     */
    diastolicPressures?: Array<number>;
    /**
     * 血糖列表 (mmol/L)
     * @type {Array<number>}
     * @memberof BiometricChartDataDto
     */
    bloodGlucoses?: Array<number>;
    /**
     * 血脂列表 (mmol/L)
     * @type {Array<number>}
     * @memberof BiometricChartDataDto
     */
    bloodLipids?: Array<number>;
    /**
     * BMI列表
     * @type {Array<number>}
     * @memberof BiometricChartDataDto
     */
    bmis?: Array<number>;
}

/**
 * Check if a given object implements the BiometricChartDataDto interface.
 */
export function instanceOfBiometricChartDataDto(value: object): value is BiometricChartDataDto {
    return true;
}

export function BiometricChartDataDtoFromJSON(json: any): BiometricChartDataDto {
    return BiometricChartDataDtoFromJSONTyped(json, false);
}

export function BiometricChartDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BiometricChartDataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'dates': json['dates'] == null ? undefined : json['dates'],
        'weights': json['weights'] == null ? undefined : json['weights'],
        'systolicPressures': json['systolicPressures'] == null ? undefined : json['systolicPressures'],
        'diastolicPressures': json['diastolicPressures'] == null ? undefined : json['diastolicPressures'],
        'bloodGlucoses': json['bloodGlucoses'] == null ? undefined : json['bloodGlucoses'],
        'bloodLipids': json['bloodLipids'] == null ? undefined : json['bloodLipids'],
        'bmis': json['bmis'] == null ? undefined : json['bmis'],
    };
}

export function BiometricChartDataDtoToJSON(json: any): BiometricChartDataDto {
    return BiometricChartDataDtoToJSONTyped(json, false);
}

export function BiometricChartDataDtoToJSONTyped(value?: BiometricChartDataDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dates': value['dates'],
        'weights': value['weights'],
        'systolicPressures': value['systolicPressures'],
        'diastolicPressures': value['diastolicPressures'],
        'bloodGlucoses': value['bloodGlucoses'],
        'bloodLipids': value['bloodLipids'],
        'bmis': value['bmis'],
    };
}

