/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 运动记录请求参数
 * @export
 * @interface ExerciseLogDto
 */
export interface ExerciseLogDto {
    /**
     * 运动类型
     * @type {string}
     * @memberof ExerciseLogDto
     */
    exerciseType: string;
    /**
     * 开始时间（时间戳格式）
     * @type {number}
     * @memberof ExerciseLogDto
     */
    startTimestamp: number;
    /**
     * 持续时间（分钟）
     * @type {number}
     * @memberof ExerciseLogDto
     */
    durationMinutes: number;
    /**
     * 运动距离（千米）
     * @type {number}
     * @memberof ExerciseLogDto
     */
    distanceKm?: number;
    /**
     * 消耗卡路里（大卡）
     * @type {number}
     * @memberof ExerciseLogDto
     */
    caloriesBurned: number;
}

/**
 * Check if a given object implements the ExerciseLogDto interface.
 */
export function instanceOfExerciseLogDto(value: object): value is ExerciseLogDto {
    if (!('exerciseType' in value) || value['exerciseType'] === undefined) return false;
    if (!('startTimestamp' in value) || value['startTimestamp'] === undefined) return false;
    if (!('durationMinutes' in value) || value['durationMinutes'] === undefined) return false;
    if (!('caloriesBurned' in value) || value['caloriesBurned'] === undefined) return false;
    return true;
}

export function ExerciseLogDtoFromJSON(json: any): ExerciseLogDto {
    return ExerciseLogDtoFromJSONTyped(json, false);
}

export function ExerciseLogDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseLogDto {
    if (json == null) {
        return json;
    }
    return {
        
        'exerciseType': json['exerciseType'],
        'startTimestamp': (new Date(json['startTimestamp'])),
        'durationMinutes': json['durationMinutes'],
        'distanceKm': json['distanceKm'] == null ? undefined : json['distanceKm'],
        'caloriesBurned': json['caloriesBurned'],
    };
}

export function ExerciseLogDtoToJSON(json: any): ExerciseLogDto {
    return ExerciseLogDtoToJSONTyped(json, false);
}

export function ExerciseLogDtoToJSONTyped(value?: ExerciseLogDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exerciseType': value['exerciseType'],
        'startTimestamp': ((value['startTimestamp'])),
        'durationMinutes': value['durationMinutes'],
        'distanceKm': value['distanceKm'],
        'caloriesBurned': value['caloriesBurned'],
    };
}

