/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExerciseLog
 */
export interface ExerciseLog {
    /**
     * 
     * @type {number}
     * @memberof ExerciseLog
     */
    logId?: number;
    /**
     * 
     * @type {number}
     * @memberof ExerciseLog
     */
    accountId?: number;
    /**
     * 
     * @type {string}
     * @memberof ExerciseLog
     */
    exerciseType?: string;
    /**
     * 
     * @type {Date}
     * @memberof ExerciseLog
     */
    startTimestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof ExerciseLog
     */
    durationMinutes?: number;
    /**
     * 
     * @type {number}
     * @memberof ExerciseLog
     */
    distanceKm?: number;
    /**
     * 
     * @type {number}
     * @memberof ExerciseLog
     */
    caloriesBurned?: number;
    /**
     * 
     * @type {Date}
     * @memberof ExerciseLog
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the ExerciseLog interface.
 */
export function instanceOfExerciseLog(value: object): value is ExerciseLog {
    return true;
}

export function ExerciseLogFromJSON(json: any): ExerciseLog {
    return ExerciseLogFromJSONTyped(json, false);
}

export function ExerciseLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseLog {
    if (json == null) {
        return json;
    }
    return {
        
        'logId': json['logId'] == null ? undefined : json['logId'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'exerciseType': json['exerciseType'] == null ? undefined : json['exerciseType'],
        'startTimestamp': json['startTimestamp'] == null ? undefined : (new Date(json['startTimestamp'])),
        'durationMinutes': json['durationMinutes'] == null ? undefined : json['durationMinutes'],
        'distanceKm': json['distanceKm'] == null ? undefined : json['distanceKm'],
        'caloriesBurned': json['caloriesBurned'] == null ? undefined : json['caloriesBurned'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function ExerciseLogToJSON(json: any): ExerciseLog {
    return ExerciseLogToJSONTyped(json, false);
}

export function ExerciseLogToJSONTyped(value?: ExerciseLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logId': value['logId'],
        'accountId': value['accountId'],
        'exerciseType': value['exerciseType'],
        'startTimestamp': value['startTimestamp'] == null ? undefined : ((value['startTimestamp']).toISOString()),
        'durationMinutes': value['durationMinutes'],
        'distanceKm': value['distanceKm'],
        'caloriesBurned': value['caloriesBurned'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

