/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthCheckReminder
 */
export interface HealthCheckReminder {
    /**
     * 
     * @type {number}
     * @memberof HealthCheckReminder
     */
    reminderId?: number;
    /**
     * 
     * @type {number}
     * @memberof HealthCheckReminder
     */
    accountId?: number;
    /**
     * 
     * @type {string}
     * @memberof HealthCheckReminder
     */
    reminderContent?: string;
    /**
     * 
     * @type {Date}
     * @memberof HealthCheckReminder
     */
    scheduledTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof HealthCheckReminder
     */
    completionStatus?: number;
    /**
     * 
     * @type {number}
     * @memberof HealthCheckReminder
     */
    checkFrequencyDays?: number;
    /**
     * 
     * @type {Date}
     * @memberof HealthCheckReminder
     */
    lastReminderSent?: Date;
    /**
     * 
     * @type {Date}
     * @memberof HealthCheckReminder
     */
    nextReminderTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof HealthCheckReminder
     */
    reminderCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof HealthCheckReminder
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the HealthCheckReminder interface.
 */
export function instanceOfHealthCheckReminder(value: object): value is HealthCheckReminder {
    return true;
}

export function HealthCheckReminderFromJSON(json: any): HealthCheckReminder {
    return HealthCheckReminderFromJSONTyped(json, false);
}

export function HealthCheckReminderFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheckReminder {
    if (json == null) {
        return json;
    }
    return {
        
        'reminderId': json['reminderId'] == null ? undefined : json['reminderId'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'reminderContent': json['reminderContent'] == null ? undefined : json['reminderContent'],
        'scheduledTime': json['scheduledTime'] == null ? undefined : (new Date(json['scheduledTime'])),
        'completionStatus': json['completionStatus'] == null ? undefined : json['completionStatus'],
        'checkFrequencyDays': json['checkFrequencyDays'] == null ? undefined : json['checkFrequencyDays'],
        'lastReminderSent': json['lastReminderSent'] == null ? undefined : (new Date(json['lastReminderSent'])),
        'nextReminderTime': json['nextReminderTime'] == null ? undefined : (new Date(json['nextReminderTime'])),
        'reminderCount': json['reminderCount'] == null ? undefined : json['reminderCount'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function HealthCheckReminderToJSON(json: any): HealthCheckReminder {
    return HealthCheckReminderToJSONTyped(json, false);
}

export function HealthCheckReminderToJSONTyped(value?: HealthCheckReminder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reminderId': value['reminderId'],
        'accountId': value['accountId'],
        'reminderContent': value['reminderContent'],
        'scheduledTime': value['scheduledTime'] == null ? undefined : ((value['scheduledTime']).toISOString()),
        'completionStatus': value['completionStatus'],
        'checkFrequencyDays': value['checkFrequencyDays'],
        'lastReminderSent': value['lastReminderSent'] == null ? undefined : ((value['lastReminderSent']).toISOString()),
        'nextReminderTime': value['nextReminderTime'] == null ? undefined : ((value['nextReminderTime']).toISOString()),
        'reminderCount': value['reminderCount'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

