/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 健康目标请求参数
 * @export
 * @interface HealthGoalDto
 */
export interface HealthGoalDto {
    /**
     * 目标类别（WEIGHT_LOSS, BLOOD_SUGAR, BLOOD_LIPID, EXERCISE_CALORIES）
     * @type {string}
     * @memberof HealthGoalDto
     */
    goalCategory: string;
    /**
     * 目标值
     * @type {number}
     * @memberof HealthGoalDto
     */
    targetValue: number;
    /**
     * 目标日期（yyyy-MM-dd）
     * @type {Date}
     * @memberof HealthGoalDto
     */
    targetDate: Date;
}

/**
 * Check if a given object implements the HealthGoalDto interface.
 */
export function instanceOfHealthGoalDto(value: object): value is HealthGoalDto {
    if (!('goalCategory' in value) || value['goalCategory'] === undefined) return false;
    if (!('targetValue' in value) || value['targetValue'] === undefined) return false;
    if (!('targetDate' in value) || value['targetDate'] === undefined) return false;
    return true;
}

export function HealthGoalDtoFromJSON(json: any): HealthGoalDto {
    return HealthGoalDtoFromJSONTyped(json, false);
}

export function HealthGoalDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthGoalDto {
    if (json == null) {
        return json;
    }
    return {
        
        'goalCategory': json['goalCategory'],
        'targetValue': json['targetValue'],
        'targetDate': (new Date(json['targetDate'])),
    };
}

export function HealthGoalDtoToJSON(json: any): HealthGoalDto {
    return HealthGoalDtoToJSONTyped(json, false);
}

export function HealthGoalDtoToJSONTyped(value?: HealthGoalDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'goalCategory': value['goalCategory'],
        'targetValue': value['targetValue'],
        'targetDate': ((value['targetDate']).toISOString()),
    };
}

