/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 体检提醒DTO
 * @export
 * @interface HealthCheckReminderDto
 */
export interface HealthCheckReminderDto {
    /**
     * 体检频率（天）
     * @type {number}
     * @memberof HealthCheckReminderDto
     */
    checkFrequencyDays?: number;
    /**
     * 体检时间
     * @type {Date}
     * @memberof HealthCheckReminderDto
     */
    scheduledTime?: Date;
    /**
     * 提醒内容
     * @type {string}
     * @memberof HealthCheckReminderDto
     */
    reminderContent?: string;
}

/**
 * Check if a given object implements the HealthCheckReminderDto interface.
 */
export function instanceOfHealthCheckReminderDto(value: object): value is HealthCheckReminderDto {
    return true;
}

export function HealthCheckReminderDtoFromJSON(json: any): HealthCheckReminderDto {
    return HealthCheckReminderDtoFromJSONTyped(json, false);
}

export function HealthCheckReminderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheckReminderDto {
    if (json == null) {
        return json;
    }
    return {
        
        'checkFrequencyDays': json['checkFrequencyDays'] == null ? undefined : json['checkFrequencyDays'],
        'scheduledTime': json['scheduledTime'] == null ? undefined : (new Date(json['scheduledTime'])),
        'reminderContent': json['reminderContent'] == null ? undefined : json['reminderContent'],
    };
}

export function HealthCheckReminderDtoToJSON(json: any): HealthCheckReminderDto {
    return HealthCheckReminderDtoToJSONTyped(json, false);
}

export function HealthCheckReminderDtoToJSONTyped(value?: HealthCheckReminderDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checkFrequencyDays': value['checkFrequencyDays'],
        'scheduledTime': value['scheduledTime'] == null ? undefined : ((value['scheduledTime']).toISOString()),
        'reminderContent': value['reminderContent'],
    };
}

