/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderItem } from './OrderItem';
import {
    OrderItemFromJSON,
    OrderItemFromJSONTyped,
    OrderItemToJSON,
    OrderItemToJSONTyped,
} from './OrderItem';
import type { DietLog } from './DietLog';
import {
    DietLogFromJSON,
    DietLogFromJSONTyped,
    DietLogToJSON,
    DietLogToJSONTyped,
} from './DietLog';

/**
 * 响应数据
 * @export
 * @interface PageDietLog
 */
export interface PageDietLog {
    /**
     * 
     * @type {Array<DietLog>}
     * @memberof PageDietLog
     */
    records?: Array<DietLog>;
    /**
     * 
     * @type {number}
     * @memberof PageDietLog
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof PageDietLog
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageDietLog
     */
    current?: number;
    /**
     * 
     * @type {Array<OrderItem>}
     * @memberof PageDietLog
     */
    orders?: Array<OrderItem>;
    /**
     * 
     * @type {PageDietLog}
     * @memberof PageDietLog
     */
    optimizeCountSql?: PageDietLog;
    /**
     * 
     * @type {PageDietLog}
     * @memberof PageDietLog
     */
    searchCount?: PageDietLog;
    /**
     * 
     * @type {boolean}
     * @memberof PageDietLog
     */
    optimizeJoinOfCountSql?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageDietLog
     */
    maxLimit?: number;
    /**
     * 
     * @type {string}
     * @memberof PageDietLog
     */
    countId?: string;
    /**
     * 
     * @type {number}
     * @memberof PageDietLog
     * @deprecated
     */
    pages?: number;
}

/**
 * Check if a given object implements the PageDietLog interface.
 */
export function instanceOfPageDietLog(value: object): value is PageDietLog {
    return true;
}

export function PageDietLogFromJSON(json: any): PageDietLog {
    return PageDietLogFromJSONTyped(json, false);
}

export function PageDietLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageDietLog {
    if (json == null) {
        return json;
    }
    return {
        
        'records': json['records'] == null ? undefined : ((json['records'] as Array<any>).map(DietLogFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'size': json['size'] == null ? undefined : json['size'],
        'current': json['current'] == null ? undefined : json['current'],
        'orders': json['orders'] == null ? undefined : ((json['orders'] as Array<any>).map(OrderItemFromJSON)),
        'optimizeCountSql': json['optimizeCountSql'] == null ? undefined : PageDietLogFromJSON(json['optimizeCountSql']),
        'searchCount': json['searchCount'] == null ? undefined : PageDietLogFromJSON(json['searchCount']),
        'optimizeJoinOfCountSql': json['optimizeJoinOfCountSql'] == null ? undefined : json['optimizeJoinOfCountSql'],
        'maxLimit': json['maxLimit'] == null ? undefined : json['maxLimit'],
        'countId': json['countId'] == null ? undefined : json['countId'],
        'pages': json['pages'] == null ? undefined : json['pages'],
    };
}

export function PageDietLogToJSON(json: any): PageDietLog {
    return PageDietLogToJSONTyped(json, false);
}

export function PageDietLogToJSONTyped(value?: PageDietLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'records': value['records'] == null ? undefined : ((value['records'] as Array<any>).map(DietLogToJSON)),
        'total': value['total'],
        'size': value['size'],
        'current': value['current'],
        'orders': value['orders'] == null ? undefined : ((value['orders'] as Array<any>).map(OrderItemToJSON)),
        'optimizeCountSql': PageDietLogToJSON(value['optimizeCountSql']),
        'searchCount': PageDietLogToJSON(value['searchCount']),
        'optimizeJoinOfCountSql': value['optimizeJoinOfCountSql'],
        'maxLimit': value['maxLimit'],
        'countId': value['countId'],
        'pages': value['pages'],
    };
}

