/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {OrderItem} from './OrderItem';
import {OrderItemFromJSON, OrderItemToJSON,} from './OrderItem';
import type {PageObject} from './PageObject';
import {PageObjectFromJSON, PageObjectToJSON,} from './PageObject';

/**
 *
 * @export
 * @interface Page
 */
export interface Page {
  /**
   *
   * @type {Array<object>}
   * @memberof Page
   */
  records?: Array<object>;
  /**
   *
   * @type {number}
   * @memberof Page
   */
  total?: number;
  /**
   *
   * @type {number}
   * @memberof Page
   */
  size?: number;
  /**
   *
   * @type {number}
   * @memberof Page
   */
  current?: number;
  /**
   *
   * @type {Array<OrderItem>}
   * @memberof Page
   */
  orders?: Array<OrderItem>;
  /**
   *
   * @type {PageObject}
   * @memberof Page
   */
  optimizeCountSql?: PageObject;
  /**
   *
   * @type {PageObject}
   * @memberof Page
   */
  searchCount?: PageObject;
  /**
   *
   * @type {boolean}
   * @memberof Page
   */
  optimizeJoinOfCountSql?: boolean;
  /**
   *
   * @type {number}
   * @memberof Page
   */
  maxLimit?: number;
  /**
   *
   * @type {string}
   * @memberof Page
   */
  countId?: string;
  /**
   *
   * @type {number}
   * @memberof Page
   * @deprecated
   */
  pages?: number;
}

/**
 * Check if a given object implements the Page interface.
 */
export function instanceOfPage(value: object): value is Page {
  return true;
}

export function PageFromJSON(json: any): Page {
  return PageFromJSONTyped(json, false);
}

export function PageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Page {
  if (json == null) {
    return json;
  }
  return {

    'records': json['records'] == null ? undefined : json['records'],
    'total': json['total'] == null ? undefined : json['total'],
    'size': json['size'] == null ? undefined : json['size'],
    'current': json['current'] == null ? undefined : json['current'],
    'orders': json['orders'] == null ? undefined : ((json['orders'] as Array<any>).map(OrderItemFromJSON)),
    'optimizeCountSql': json['optimizeCountSql'] == null ? undefined : PageObjectFromJSON(json['optimizeCountSql']),
    'searchCount': json['searchCount'] == null ? undefined : PageObjectFromJSON(json['searchCount']),
    'optimizeJoinOfCountSql': json['optimizeJoinOfCountSql'] == null ? undefined : json['optimizeJoinOfCountSql'],
    'maxLimit': json['maxLimit'] == null ? undefined : json['maxLimit'],
    'countId': json['countId'] == null ? undefined : json['countId'],
    'pages': json['pages'] == null ? undefined : json['pages'],
  };
}

export function PageToJSON(json: any): Page {
  return PageToJSONTyped(json, false);
}

export function PageToJSONTyped(value?: Page | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'records': value['records'],
    'total': value['total'],
    'size': value['size'],
    'current': value['current'],
    'orders': value['orders'] == null ? undefined : ((value['orders'] as Array<any>).map(OrderItemToJSON)),
    'optimizeCountSql': PageObjectToJSON(value['optimizeCountSql']),
    'searchCount': PageObjectToJSON(value['searchCount']),
    'optimizeJoinOfCountSql': value['optimizeJoinOfCountSql'],
    'maxLimit': value['maxLimit'],
    'countId': value['countId'],
    'pages': value['pages'],
  };
}

