/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BiometricRecordVo } from './BiometricRecordVo';
import {
    BiometricRecordVoFromJSON,
    BiometricRecordVoFromJSONTyped,
    BiometricRecordVoToJSON,
    BiometricRecordVoToJSONTyped,
} from './BiometricRecordVo';
import type { OrderItem } from './OrderItem';
import {
    OrderItemFromJSON,
    OrderItemFromJSONTyped,
    OrderItemToJSON,
    OrderItemToJSONTyped,
} from './OrderItem';

/**
 * 响应数据
 * @export
 * @interface PageBiometricRecordVo
 */
export interface PageBiometricRecordVo {
    /**
     * 
     * @type {Array<BiometricRecordVo>}
     * @memberof PageBiometricRecordVo
     */
    records?: Array<BiometricRecordVo>;
    /**
     * 
     * @type {number}
     * @memberof PageBiometricRecordVo
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof PageBiometricRecordVo
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageBiometricRecordVo
     */
    current?: number;
    /**
     * 
     * @type {Array<OrderItem>}
     * @memberof PageBiometricRecordVo
     */
    orders?: Array<OrderItem>;
    /**
     * 
     * @type {PageBiometricRecordVo}
     * @memberof PageBiometricRecordVo
     */
    optimizeCountSql?: PageBiometricRecordVo;
    /**
     * 
     * @type {PageBiometricRecordVo}
     * @memberof PageBiometricRecordVo
     */
    searchCount?: PageBiometricRecordVo;
    /**
     * 
     * @type {boolean}
     * @memberof PageBiometricRecordVo
     */
    optimizeJoinOfCountSql?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageBiometricRecordVo
     */
    maxLimit?: number;
    /**
     * 
     * @type {string}
     * @memberof PageBiometricRecordVo
     */
    countId?: string;
    /**
     * 
     * @type {number}
     * @memberof PageBiometricRecordVo
     * @deprecated
     */
    pages?: number;
}

/**
 * Check if a given object implements the PageBiometricRecordVo interface.
 */
export function instanceOfPageBiometricRecordVo(value: object): value is PageBiometricRecordVo {
    return true;
}

export function PageBiometricRecordVoFromJSON(json: any): PageBiometricRecordVo {
    return PageBiometricRecordVoFromJSONTyped(json, false);
}

export function PageBiometricRecordVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageBiometricRecordVo {
    if (json == null) {
        return json;
    }
    return {
        
        'records': json['records'] == null ? undefined : ((json['records'] as Array<any>).map(BiometricRecordVoFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'size': json['size'] == null ? undefined : json['size'],
        'current': json['current'] == null ? undefined : json['current'],
        'orders': json['orders'] == null ? undefined : ((json['orders'] as Array<any>).map(OrderItemFromJSON)),
        'optimizeCountSql': json['optimizeCountSql'] == null ? undefined : PageBiometricRecordVoFromJSON(json['optimizeCountSql']),
        'searchCount': json['searchCount'] == null ? undefined : PageBiometricRecordVoFromJSON(json['searchCount']),
        'optimizeJoinOfCountSql': json['optimizeJoinOfCountSql'] == null ? undefined : json['optimizeJoinOfCountSql'],
        'maxLimit': json['maxLimit'] == null ? undefined : json['maxLimit'],
        'countId': json['countId'] == null ? undefined : json['countId'],
        'pages': json['pages'] == null ? undefined : json['pages'],
    };
}

export function PageBiometricRecordVoToJSON(json: any): PageBiometricRecordVo {
    return PageBiometricRecordVoToJSONTyped(json, false);
}

export function PageBiometricRecordVoToJSONTyped(value?: PageBiometricRecordVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'records': value['records'] == null ? undefined : ((value['records'] as Array<any>).map(BiometricRecordVoToJSON)),
        'total': value['total'],
        'size': value['size'],
        'current': value['current'],
        'orders': value['orders'] == null ? undefined : ((value['orders'] as Array<any>).map(OrderItemToJSON)),
        'optimizeCountSql': PageBiometricRecordVoToJSON(value['optimizeCountSql']),
        'searchCount': PageBiometricRecordVoToJSON(value['searchCount']),
        'optimizeJoinOfCountSql': value['optimizeJoinOfCountSql'],
        'maxLimit': value['maxLimit'],
        'countId': value['countId'],
        'pages': value['pages'],
    };
}

