/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MedicationReminder } from './MedicationReminder';
import {
    MedicationReminderFromJSON,
    MedicationReminderFromJSONTyped,
    MedicationReminderToJSON,
    MedicationReminderToJSONTyped,
} from './MedicationReminder';
import type { OrderItem } from './OrderItem';
import {
    OrderItemFromJSON,
    OrderItemFromJSONTyped,
    OrderItemToJSON,
    OrderItemToJSONTyped,
} from './OrderItem';

/**
 * 响应数据
 * @export
 * @interface PageMedicationReminder
 */
export interface PageMedicationReminder {
    /**
     * 
     * @type {Array<MedicationReminder>}
     * @memberof PageMedicationReminder
     */
    records?: Array<MedicationReminder>;
    /**
     * 
     * @type {number}
     * @memberof PageMedicationReminder
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMedicationReminder
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMedicationReminder
     */
    current?: number;
    /**
     * 
     * @type {Array<OrderItem>}
     * @memberof PageMedicationReminder
     */
    orders?: Array<OrderItem>;
    /**
     * 
     * @type {PageMedicationReminder}
     * @memberof PageMedicationReminder
     */
    optimizeCountSql?: PageMedicationReminder;
    /**
     * 
     * @type {PageMedicationReminder}
     * @memberof PageMedicationReminder
     */
    searchCount?: PageMedicationReminder;
    /**
     * 
     * @type {boolean}
     * @memberof PageMedicationReminder
     */
    optimizeJoinOfCountSql?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageMedicationReminder
     */
    maxLimit?: number;
    /**
     * 
     * @type {string}
     * @memberof PageMedicationReminder
     */
    countId?: string;
    /**
     * 
     * @type {number}
     * @memberof PageMedicationReminder
     * @deprecated
     */
    pages?: number;
}

/**
 * Check if a given object implements the PageMedicationReminder interface.
 */
export function instanceOfPageMedicationReminder(value: object): value is PageMedicationReminder {
    return true;
}

export function PageMedicationReminderFromJSON(json: any): PageMedicationReminder {
    return PageMedicationReminderFromJSONTyped(json, false);
}

export function PageMedicationReminderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageMedicationReminder {
    if (json == null) {
        return json;
    }
    return {
        
        'records': json['records'] == null ? undefined : ((json['records'] as Array<any>).map(MedicationReminderFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'size': json['size'] == null ? undefined : json['size'],
        'current': json['current'] == null ? undefined : json['current'],
        'orders': json['orders'] == null ? undefined : ((json['orders'] as Array<any>).map(OrderItemFromJSON)),
        'optimizeCountSql': json['optimizeCountSql'] == null ? undefined : PageMedicationReminderFromJSON(json['optimizeCountSql']),
        'searchCount': json['searchCount'] == null ? undefined : PageMedicationReminderFromJSON(json['searchCount']),
        'optimizeJoinOfCountSql': json['optimizeJoinOfCountSql'] == null ? undefined : json['optimizeJoinOfCountSql'],
        'maxLimit': json['maxLimit'] == null ? undefined : json['maxLimit'],
        'countId': json['countId'] == null ? undefined : json['countId'],
        'pages': json['pages'] == null ? undefined : json['pages'],
    };
}

export function PageMedicationReminderToJSON(json: any): PageMedicationReminder {
    return PageMedicationReminderToJSONTyped(json, false);
}

export function PageMedicationReminderToJSONTyped(value?: PageMedicationReminder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'records': value['records'] == null ? undefined : ((value['records'] as Array<any>).map(MedicationReminderToJSON)),
        'total': value['total'],
        'size': value['size'],
        'current': value['current'],
        'orders': value['orders'] == null ? undefined : ((value['orders'] as Array<any>).map(OrderItemToJSON)),
        'optimizeCountSql': PageMedicationReminderToJSON(value['optimizeCountSql']),
        'searchCount': PageMedicationReminderToJSON(value['searchCount']),
        'optimizeJoinOfCountSql': value['optimizeJoinOfCountSql'],
        'maxLimit': value['maxLimit'],
        'countId': value['countId'],
        'pages': value['pages'],
    };
}

