/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HealthCheckReminder } from './HealthCheckReminder';
import {
    HealthCheckReminderFromJSON,
    HealthCheckReminderFromJSONTyped,
    HealthCheckReminderToJSON,
    HealthCheckReminderToJSONTyped,
} from './HealthCheckReminder';
import type { OrderItem } from './OrderItem';
import {
    OrderItemFromJSON,
    OrderItemFromJSONTyped,
    OrderItemToJSON,
    OrderItemToJSONTyped,
} from './OrderItem';

/**
 * 响应数据
 * @export
 * @interface PageHealthCheckReminder
 */
export interface PageHealthCheckReminder {
    /**
     * 
     * @type {Array<HealthCheckReminder>}
     * @memberof PageHealthCheckReminder
     */
    records?: Array<HealthCheckReminder>;
    /**
     * 
     * @type {number}
     * @memberof PageHealthCheckReminder
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof PageHealthCheckReminder
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageHealthCheckReminder
     */
    current?: number;
    /**
     * 
     * @type {Array<OrderItem>}
     * @memberof PageHealthCheckReminder
     */
    orders?: Array<OrderItem>;
    /**
     * 
     * @type {PageHealthCheckReminder}
     * @memberof PageHealthCheckReminder
     */
    optimizeCountSql?: PageHealthCheckReminder;
    /**
     * 
     * @type {PageHealthCheckReminder}
     * @memberof PageHealthCheckReminder
     */
    searchCount?: PageHealthCheckReminder;
    /**
     * 
     * @type {boolean}
     * @memberof PageHealthCheckReminder
     */
    optimizeJoinOfCountSql?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageHealthCheckReminder
     */
    maxLimit?: number;
    /**
     * 
     * @type {string}
     * @memberof PageHealthCheckReminder
     */
    countId?: string;
    /**
     * 
     * @type {number}
     * @memberof PageHealthCheckReminder
     * @deprecated
     */
    pages?: number;
}

/**
 * Check if a given object implements the PageHealthCheckReminder interface.
 */
export function instanceOfPageHealthCheckReminder(value: object): value is PageHealthCheckReminder {
    return true;
}

export function PageHealthCheckReminderFromJSON(json: any): PageHealthCheckReminder {
    return PageHealthCheckReminderFromJSONTyped(json, false);
}

export function PageHealthCheckReminderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageHealthCheckReminder {
    if (json == null) {
        return json;
    }
    return {
        
        'records': json['records'] == null ? undefined : ((json['records'] as Array<any>).map(HealthCheckReminderFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'size': json['size'] == null ? undefined : json['size'],
        'current': json['current'] == null ? undefined : json['current'],
        'orders': json['orders'] == null ? undefined : ((json['orders'] as Array<any>).map(OrderItemFromJSON)),
        'optimizeCountSql': json['optimizeCountSql'] == null ? undefined : PageHealthCheckReminderFromJSON(json['optimizeCountSql']),
        'searchCount': json['searchCount'] == null ? undefined : PageHealthCheckReminderFromJSON(json['searchCount']),
        'optimizeJoinOfCountSql': json['optimizeJoinOfCountSql'] == null ? undefined : json['optimizeJoinOfCountSql'],
        'maxLimit': json['maxLimit'] == null ? undefined : json['maxLimit'],
        'countId': json['countId'] == null ? undefined : json['countId'],
        'pages': json['pages'] == null ? undefined : json['pages'],
    };
}

export function PageHealthCheckReminderToJSON(json: any): PageHealthCheckReminder {
    return PageHealthCheckReminderToJSONTyped(json, false);
}

export function PageHealthCheckReminderToJSONTyped(value?: PageHealthCheckReminder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'records': value['records'] == null ? undefined : ((value['records'] as Array<any>).map(HealthCheckReminderToJSON)),
        'total': value['total'],
        'size': value['size'],
        'current': value['current'],
        'orders': value['orders'] == null ? undefined : ((value['orders'] as Array<any>).map(OrderItemToJSON)),
        'optimizeCountSql': PageHealthCheckReminderToJSON(value['optimizeCountSql']),
        'searchCount': PageHealthCheckReminderToJSON(value['searchCount']),
        'optimizeJoinOfCountSql': value['optimizeJoinOfCountSql'],
        'maxLimit': value['maxLimit'],
        'countId': value['countId'],
        'pages': value['pages'],
    };
}

