/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {PostApiAuthLogin200ResponseData} from './PostApiAuthLogin200ResponseData';
import {
  PostApiAuthLogin200ResponseDataFromJSON,
  PostApiAuthLogin200ResponseDataToJSON,
} from './PostApiAuthLogin200ResponseData';

/**
 *
 * @export
 * @interface PostApiAuthLogin200Response
 */
export interface PostApiAuthLogin200Response {
  /**
   *
   * @type {number}
   * @memberof PostApiAuthLogin200Response
   */
  code: number;
  /**
   *
   * @type {string}
   * @memberof PostApiAuthLogin200Response
   */
  msg: string;
  /**
   *
   * @type {PostApiAuthLogin200ResponseData}
   * @memberof PostApiAuthLogin200Response
   */
  data: PostApiAuthLogin200ResponseData;
}

/**
 * Check if a given object implements the PostApiAuthLogin200Response interface.
 */
export function instanceOfPostApiAuthLogin200Response(value: object): value is PostApiAuthLogin200Response {
  if (!('code' in value) || value['code'] === undefined) return false;
  if (!('msg' in value) || value['msg'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function PostApiAuthLogin200ResponseFromJSON(json: any): PostApiAuthLogin200Response {
  return PostApiAuthLogin200ResponseFromJSONTyped(json, false);
}

export function PostApiAuthLogin200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiAuthLogin200Response {
  if (json == null) {
    return json;
  }
  return {

    'code': json['code'],
    'msg': json['msg'],
    'data': PostApiAuthLogin200ResponseDataFromJSON(json['data']),
  };
}

export function PostApiAuthLogin200ResponseToJSON(json: any): PostApiAuthLogin200Response {
  return PostApiAuthLogin200ResponseToJSONTyped(json, false);
}

export function PostApiAuthLogin200ResponseToJSONTyped(value?: PostApiAuthLogin200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'code': value['code'],
    'msg': value['msg'],
    'data': PostApiAuthLogin200ResponseDataToJSON(value['data']),
  };
}

