/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PostApiAuthLogin200ResponseData
 */
export interface PostApiAuthLogin200ResponseData {
  /**
   *
   * @type {string}
   * @memberof PostApiAuthLogin200ResponseData
   */
  token: string;
}

/**
 * Check if a given object implements the PostApiAuthLogin200ResponseData interface.
 */
export function instanceOfPostApiAuthLogin200ResponseData(value: object): value is PostApiAuthLogin200ResponseData {
  if (!('token' in value) || value['token'] === undefined) return false;
  return true;
}

export function PostApiAuthLogin200ResponseDataFromJSON(json: any): PostApiAuthLogin200ResponseData {
  return PostApiAuthLogin200ResponseDataFromJSONTyped(json, false);
}

export function PostApiAuthLogin200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiAuthLogin200ResponseData {
  if (json == null) {
    return json;
  }
  return {

    'token': json['token'],
  };
}

export function PostApiAuthLogin200ResponseDataToJSON(json: any): PostApiAuthLogin200ResponseData {
  return PostApiAuthLogin200ResponseDataToJSONTyped(json, false);
}

export function PostApiAuthLogin200ResponseDataToJSONTyped(value?: PostApiAuthLogin200ResponseData | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'token': value['token'],
  };
}

