/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 注册请求参数
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
  /**
   * 用户名
   * @type {string}
   * @memberof RegisterDto
   */
  username: string;
  /**
   * 邮箱地址
   * @type {string}
   * @memberof RegisterDto
   */
  email: string;
  /**
   * 密码（6-20位字符）
   * @type {string}
   * @memberof RegisterDto
   */
  password: string;
  /**
   * 邮箱验证码
   * @type {string}
   * @memberof RegisterDto
   */
  code: string;
}

/**
 * Check if a given object implements the RegisterDto interface.
 */
export function instanceOfRegisterDto(value: object): value is RegisterDto {
  if (!('username' in value) || value['username'] === undefined) return false;
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('password' in value) || value['password'] === undefined) return false;
  if (!('code' in value) || value['code'] === undefined) return false;
  return true;
}

export function RegisterDtoFromJSON(json: any): RegisterDto {
  return RegisterDtoFromJSONTyped(json, false);
}

export function RegisterDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDto {
  if (json == null) {
    return json;
  }
  return {

    'username': json['username'],
    'email': json['email'],
    'password': json['password'],
    'code': json['code'],
  };
}

export function RegisterDtoToJSON(json: any): RegisterDto {
  return RegisterDtoToJSONTyped(json, false);
}

export function RegisterDtoToJSONTyped(value?: RegisterDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'username': value['username'],
    'email': value['email'],
    'password': value['password'],
    'code': value['code'],
  };
}

