/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageSleepLog } from './PageSleepLog';
import {
    PageSleepLogFromJSON,
    PageSleepLogFromJSONTyped,
    PageSleepLogToJSON,
    PageSleepLogToJSONTyped,
} from './PageSleepLog';

/**
 * 通用响应结果
 * @export
 * @interface ResponseResultPageSleepLog
 */
export interface ResponseResultPageSleepLog {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultPageSleepLog
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultPageSleepLog
     */
    msg?: string;
    /**
     * 
     * @type {PageSleepLog}
     * @memberof ResponseResultPageSleepLog
     */
    data?: PageSleepLog;
}

/**
 * Check if a given object implements the ResponseResultPageSleepLog interface.
 */
export function instanceOfResponseResultPageSleepLog(value: object): value is ResponseResultPageSleepLog {
    return true;
}

export function ResponseResultPageSleepLogFromJSON(json: any): ResponseResultPageSleepLog {
    return ResponseResultPageSleepLogFromJSONTyped(json, false);
}

export function ResponseResultPageSleepLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultPageSleepLog {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : PageSleepLogFromJSON(json['data']),
    };
}

export function ResponseResultPageSleepLogToJSON(json: any): ResponseResultPageSleepLog {
    return ResponseResultPageSleepLogToJSONTyped(json, false);
}

export function ResponseResultPageSleepLogToJSONTyped(value?: ResponseResultPageSleepLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': PageSleepLogToJSON(value['data']),
    };
}

