/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 通用响应结果
 * @export
 * @interface ResponseResultVoid
 */
export interface ResponseResultVoid {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultVoid
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultVoid
     */
    msg?: string;
    /**
     * 响应数据
     * @type {object}
     * @memberof ResponseResultVoid
     */
    data?: object;
}

/**
 * Check if a given object implements the ResponseResultVoid interface.
 */
export function instanceOfResponseResultVoid(value: object): value is ResponseResultVoid {
    return true;
}

export function ResponseResultVoidFromJSON(json: any): ResponseResultVoid {
    return ResponseResultVoidFromJSONTyped(json, false);
}

export function ResponseResultVoidFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultVoid {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ResponseResultVoidToJSON(json: any): ResponseResultVoid {
    return ResponseResultVoidToJSONTyped(json, false);
}

export function ResponseResultVoidToJSONTyped(value?: ResponseResultVoid | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': value['data'],
    };
}

