/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HealthCheckReminderDto } from './HealthCheckReminderDto';
import {
    HealthCheckReminderDtoFromJSON,
    HealthCheckReminderDtoFromJSONTyped,
    HealthCheckReminderDtoToJSON,
    HealthCheckReminderDtoToJSONTyped,
} from './HealthCheckReminderDto';

/**
 * 通用响应结果
 * @export
 * @interface ResponseResultHealthCheckReminderDto
 */
export interface ResponseResultHealthCheckReminderDto {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultHealthCheckReminderDto
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultHealthCheckReminderDto
     */
    msg?: string;
    /**
     * 
     * @type {HealthCheckReminderDto}
     * @memberof ResponseResultHealthCheckReminderDto
     */
    data?: HealthCheckReminderDto;
}

/**
 * Check if a given object implements the ResponseResultHealthCheckReminderDto interface.
 */
export function instanceOfResponseResultHealthCheckReminderDto(value: object): value is ResponseResultHealthCheckReminderDto {
    return true;
}

export function ResponseResultHealthCheckReminderDtoFromJSON(json: any): ResponseResultHealthCheckReminderDto {
    return ResponseResultHealthCheckReminderDtoFromJSONTyped(json, false);
}

export function ResponseResultHealthCheckReminderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultHealthCheckReminderDto {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : HealthCheckReminderDtoFromJSON(json['data']),
    };
}

export function ResponseResultHealthCheckReminderDtoToJSON(json: any): ResponseResultHealthCheckReminderDto {
    return ResponseResultHealthCheckReminderDtoToJSONTyped(json, false);
}

export function ResponseResultHealthCheckReminderDtoToJSONTyped(value?: ResponseResultHealthCheckReminderDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': HealthCheckReminderDtoToJSON(value['data']),
    };
}

