/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageBiometricRecord } from './PageBiometricRecord';
import {
    PageBiometricRecordFromJSON,
    PageBiometricRecordFromJSONTyped,
    PageBiometricRecordToJSON,
    PageBiometricRecordToJSONTyped,
} from './PageBiometricRecord';

/**
 * 通用响应结果
 * @export
 * @interface ResponseResultPageBiometricRecord
 */
export interface ResponseResultPageBiometricRecord {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultPageBiometricRecord
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultPageBiometricRecord
     */
    msg?: string;
    /**
     * 
     * @type {PageBiometricRecord}
     * @memberof ResponseResultPageBiometricRecord
     */
    data?: PageBiometricRecord;
}

/**
 * Check if a given object implements the ResponseResultPageBiometricRecord interface.
 */
export function instanceOfResponseResultPageBiometricRecord(value: object): value is ResponseResultPageBiometricRecord {
    return true;
}

export function ResponseResultPageBiometricRecordFromJSON(json: any): ResponseResultPageBiometricRecord {
    return ResponseResultPageBiometricRecordFromJSONTyped(json, false);
}

export function ResponseResultPageBiometricRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultPageBiometricRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : PageBiometricRecordFromJSON(json['data']),
    };
}

export function ResponseResultPageBiometricRecordToJSON(json: any): ResponseResultPageBiometricRecord {
    return ResponseResultPageBiometricRecordToJSONTyped(json, false);
}

export function ResponseResultPageBiometricRecordToJSONTyped(value?: ResponseResultPageBiometricRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': PageBiometricRecordToJSON(value['data']),
    };
}

