/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 通用响应结果
 * @export
 * @interface ResponseResultMapStringObject
 */
export interface ResponseResultMapStringObject {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultMapStringObject
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultMapStringObject
     */
    msg?: string;
    /**
     * 响应数据
     * @type {{ [key: string]: object; }}
     * @memberof ResponseResultMapStringObject
     */
    data?: { [key: string]: object; };
}

/**
 * Check if a given object implements the ResponseResultMapStringObject interface.
 */
export function instanceOfResponseResultMapStringObject(value: object): value is ResponseResultMapStringObject {
    return true;
}

export function ResponseResultMapStringObjectFromJSON(json: any): ResponseResultMapStringObject {
    return ResponseResultMapStringObjectFromJSONTyped(json, false);
}

export function ResponseResultMapStringObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultMapStringObject {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ResponseResultMapStringObjectToJSON(json: any): ResponseResultMapStringObject {
    return ResponseResultMapStringObjectToJSONTyped(json, false);
}

export function ResponseResultMapStringObjectToJSONTyped(value?: ResponseResultMapStringObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': value['data'],
    };
}

