/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageDietLog } from './PageDietLog';
import {
    PageDietLogFromJSON,
    PageDietLogFromJSONTyped,
    PageDietLogToJSON,
    PageDietLogToJSONTyped,
} from './PageDietLog';

/**
 * 通用响应结果
 * @export
 * @interface ResponseResultPageDietLog
 */
export interface ResponseResultPageDietLog {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultPageDietLog
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultPageDietLog
     */
    msg?: string;
    /**
     * 
     * @type {PageDietLog}
     * @memberof ResponseResultPageDietLog
     */
    data?: PageDietLog;
}

/**
 * Check if a given object implements the ResponseResultPageDietLog interface.
 */
export function instanceOfResponseResultPageDietLog(value: object): value is ResponseResultPageDietLog {
    return true;
}

export function ResponseResultPageDietLogFromJSON(json: any): ResponseResultPageDietLog {
    return ResponseResultPageDietLogFromJSONTyped(json, false);
}

export function ResponseResultPageDietLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultPageDietLog {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : PageDietLogFromJSON(json['data']),
    };
}

export function ResponseResultPageDietLogToJSON(json: any): ResponseResultPageDietLog {
    return ResponseResultPageDietLogToJSONTyped(json, false);
}

export function ResponseResultPageDietLogToJSONTyped(value?: ResponseResultPageDietLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': PageDietLogToJSON(value['data']),
    };
}

