/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SleepLog } from './SleepLog';
import {
    SleepLogFromJSON,
    SleepLogFromJSONTyped,
    SleepLogToJSON,
    SleepLogToJSONTyped,
} from './SleepLog';

/**
 * 通用响应结果
 * @export
 * @interface ResponseResultSleepLog
 */
export interface ResponseResultSleepLog {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultSleepLog
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultSleepLog
     */
    msg?: string;
    /**
     * 
     * @type {SleepLog}
     * @memberof ResponseResultSleepLog
     */
    data?: SleepLog;
}

/**
 * Check if a given object implements the ResponseResultSleepLog interface.
 */
export function instanceOfResponseResultSleepLog(value: object): value is ResponseResultSleepLog {
    return true;
}

export function ResponseResultSleepLogFromJSON(json: any): ResponseResultSleepLog {
    return ResponseResultSleepLogFromJSONTyped(json, false);
}

export function ResponseResultSleepLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultSleepLog {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : SleepLogFromJSON(json['data']),
    };
}

export function ResponseResultSleepLogToJSON(json: any): ResponseResultSleepLog {
    return ResponseResultSleepLogToJSONTyped(json, false);
}

export function ResponseResultSleepLogToJSONTyped(value?: ResponseResultSleepLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': SleepLogToJSON(value['data']),
    };
}

