/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ResponseResult
 */
export interface ResponseResult {
  /**
   *
   * @type {number}
   * @memberof ResponseResult
   */
  code?: number;
  /**
   *
   * @type {string}
   * @memberof ResponseResult
   */
  msg?: string;
  /**
   *
   * @type {object}
   * @memberof ResponseResult
   */
  data?: object;
}

/**
 * Check if a given object implements the ResponseResult interface.
 */
export function instanceOfResponseResult(value: object): value is ResponseResult {
  return true;
}

export function ResponseResultFromJSON(json: any): ResponseResult {
  return ResponseResultFromJSONTyped(json, false);
}

export function ResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResult {
  if (json == null) {
    return json;
  }
  return {

    'code': json['code'] == null ? undefined : json['code'],
    'msg': json['msg'] == null ? undefined : json['msg'],
    'data': json['data'] == null ? undefined : json['data'],
  };
}

export function ResponseResultToJSON(json: any): ResponseResult {
  return ResponseResultToJSONTyped(json, false);
}

export function ResponseResultToJSONTyped(value?: ResponseResult | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'code': value['code'],
    'msg': value['msg'],
    'data': value['data'],
  };
}

