/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageExerciseLog } from './PageExerciseLog';
import {
    PageExerciseLogFromJSON,
    PageExerciseLogFromJSONTyped,
    PageExerciseLogToJSON,
    PageExerciseLogToJSONTyped,
} from './PageExerciseLog';

/**
 * 通用响应结果
 * @export
 * @interface ResponseResultPageExerciseLog
 */
export interface ResponseResultPageExerciseLog {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultPageExerciseLog
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultPageExerciseLog
     */
    msg?: string;
    /**
     * 
     * @type {PageExerciseLog}
     * @memberof ResponseResultPageExerciseLog
     */
    data?: PageExerciseLog;
}

/**
 * Check if a given object implements the ResponseResultPageExerciseLog interface.
 */
export function instanceOfResponseResultPageExerciseLog(value: object): value is ResponseResultPageExerciseLog {
    return true;
}

export function ResponseResultPageExerciseLogFromJSON(json: any): ResponseResultPageExerciseLog {
    return ResponseResultPageExerciseLogFromJSONTyped(json, false);
}

export function ResponseResultPageExerciseLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultPageExerciseLog {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : PageExerciseLogFromJSON(json['data']),
    };
}

export function ResponseResultPageExerciseLogToJSON(json: any): ResponseResultPageExerciseLog {
    return ResponseResultPageExerciseLogToJSONTyped(json, false);
}

export function ResponseResultPageExerciseLogToJSONTyped(value?: ResponseResultPageExerciseLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': PageExerciseLogToJSON(value['data']),
    };
}

