/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMedicationReminder } from './PageMedicationReminder';
import {
    PageMedicationReminderFromJSON,
    PageMedicationReminderFromJSONTyped,
    PageMedicationReminderToJSON,
    PageMedicationReminderToJSONTyped,
} from './PageMedicationReminder';

/**
 * 通用响应结果
 * @export
 * @interface ResponseResultPageMedicationReminder
 */
export interface ResponseResultPageMedicationReminder {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultPageMedicationReminder
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultPageMedicationReminder
     */
    msg?: string;
    /**
     * 
     * @type {PageMedicationReminder}
     * @memberof ResponseResultPageMedicationReminder
     */
    data?: PageMedicationReminder;
}

/**
 * Check if a given object implements the ResponseResultPageMedicationReminder interface.
 */
export function instanceOfResponseResultPageMedicationReminder(value: object): value is ResponseResultPageMedicationReminder {
    return true;
}

export function ResponseResultPageMedicationReminderFromJSON(json: any): ResponseResultPageMedicationReminder {
    return ResponseResultPageMedicationReminderFromJSONTyped(json, false);
}

export function ResponseResultPageMedicationReminderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultPageMedicationReminder {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : PageMedicationReminderFromJSON(json['data']),
    };
}

export function ResponseResultPageMedicationReminderToJSON(json: any): ResponseResultPageMedicationReminder {
    return ResponseResultPageMedicationReminderToJSONTyped(json, false);
}

export function ResponseResultPageMedicationReminderToJSONTyped(value?: ResponseResultPageMedicationReminder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': PageMedicationReminderToJSON(value['data']),
    };
}

