/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MedicationReminder } from './MedicationReminder';
import {
    MedicationReminderFromJSON,
    MedicationReminderFromJSONTyped,
    MedicationReminderToJSON,
    MedicationReminderToJSONTyped,
} from './MedicationReminder';

/**
 * 通用响应结果
 * @export
 * @interface ResponseResultListMedicationReminder
 */
export interface ResponseResultListMedicationReminder {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultListMedicationReminder
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultListMedicationReminder
     */
    msg?: string;
    /**
     * 响应数据
     * @type {Array<MedicationReminder>}
     * @memberof ResponseResultListMedicationReminder
     */
    data?: Array<MedicationReminder>;
}

/**
 * Check if a given object implements the ResponseResultListMedicationReminder interface.
 */
export function instanceOfResponseResultListMedicationReminder(value: object): value is ResponseResultListMedicationReminder {
    return true;
}

export function ResponseResultListMedicationReminderFromJSON(json: any): ResponseResultListMedicationReminder {
    return ResponseResultListMedicationReminderFromJSONTyped(json, false);
}

export function ResponseResultListMedicationReminderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultListMedicationReminder {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MedicationReminderFromJSON)),
    };
}

export function ResponseResultListMedicationReminderToJSON(json: any): ResponseResultListMedicationReminder {
    return ResponseResultListMedicationReminderToJSONTyped(json, false);
}

export function ResponseResultListMedicationReminderToJSONTyped(value?: ResponseResultListMedicationReminder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MedicationReminderToJSON)),
    };
}

