/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageHealthCheckReminder } from './PageHealthCheckReminder';
import {
    PageHealthCheckReminderFromJSON,
    PageHealthCheckReminderFromJSONTyped,
    PageHealthCheckReminderToJSON,
    PageHealthCheckReminderToJSONTyped,
} from './PageHealthCheckReminder';

/**
 * 通用响应结果
 * @export
 * @interface ResponseResultPageHealthCheckReminder
 */
export interface ResponseResultPageHealthCheckReminder {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultPageHealthCheckReminder
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultPageHealthCheckReminder
     */
    msg?: string;
    /**
     * 
     * @type {PageHealthCheckReminder}
     * @memberof ResponseResultPageHealthCheckReminder
     */
    data?: PageHealthCheckReminder;
}

/**
 * Check if a given object implements the ResponseResultPageHealthCheckReminder interface.
 */
export function instanceOfResponseResultPageHealthCheckReminder(value: object): value is ResponseResultPageHealthCheckReminder {
    return true;
}

export function ResponseResultPageHealthCheckReminderFromJSON(json: any): ResponseResultPageHealthCheckReminder {
    return ResponseResultPageHealthCheckReminderFromJSONTyped(json, false);
}

export function ResponseResultPageHealthCheckReminderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultPageHealthCheckReminder {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : PageHealthCheckReminderFromJSON(json['data']),
    };
}

export function ResponseResultPageHealthCheckReminderToJSON(json: any): ResponseResultPageHealthCheckReminder {
    return ResponseResultPageHealthCheckReminderToJSONTyped(json, false);
}

export function ResponseResultPageHealthCheckReminderToJSONTyped(value?: ResponseResultPageHealthCheckReminder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': PageHealthCheckReminderToJSON(value['data']),
    };
}

