/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BiometricChartDataDto } from './BiometricChartDataDto';
import {
    BiometricChartDataDtoFromJSON,
    BiometricChartDataDtoFromJSONTyped,
    BiometricChartDataDtoToJSON,
    BiometricChartDataDtoToJSONTyped,
} from './BiometricChartDataDto';

/**
 * 通用响应结果
 * @export
 * @interface ResponseResultBiometricChartDataDto
 */
export interface ResponseResultBiometricChartDataDto {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultBiometricChartDataDto
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultBiometricChartDataDto
     */
    msg?: string;
    /**
     * 
     * @type {BiometricChartDataDto}
     * @memberof ResponseResultBiometricChartDataDto
     */
    data?: BiometricChartDataDto;
}

/**
 * Check if a given object implements the ResponseResultBiometricChartDataDto interface.
 */
export function instanceOfResponseResultBiometricChartDataDto(value: object): value is ResponseResultBiometricChartDataDto {
    return true;
}

export function ResponseResultBiometricChartDataDtoFromJSON(json: any): ResponseResultBiometricChartDataDto {
    return ResponseResultBiometricChartDataDtoFromJSONTyped(json, false);
}

export function ResponseResultBiometricChartDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultBiometricChartDataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : BiometricChartDataDtoFromJSON(json['data']),
    };
}

export function ResponseResultBiometricChartDataDtoToJSON(json: any): ResponseResultBiometricChartDataDto {
    return ResponseResultBiometricChartDataDtoToJSONTyped(json, false);
}

export function ResponseResultBiometricChartDataDtoToJSONTyped(value?: ResponseResultBiometricChartDataDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': BiometricChartDataDtoToJSON(value['data']),
    };
}

