/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 通用响应结果
 * @export
 * @interface ResponseResultMapStringString
 */
export interface ResponseResultMapStringString {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultMapStringString
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultMapStringString
     */
    msg?: string;
    /**
     * 响应数据
     * @type {{ [key: string]: string; }}
     * @memberof ResponseResultMapStringString
     */
    data?: { [key: string]: string; };
}

/**
 * Check if a given object implements the ResponseResultMapStringString interface.
 */
export function instanceOfResponseResultMapStringString(value: object): value is ResponseResultMapStringString {
    return true;
}

export function ResponseResultMapStringStringFromJSON(json: any): ResponseResultMapStringString {
    return ResponseResultMapStringStringFromJSONTyped(json, false);
}

export function ResponseResultMapStringStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultMapStringString {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ResponseResultMapStringStringToJSON(json: any): ResponseResultMapStringString {
    return ResponseResultMapStringStringToJSONTyped(json, false);
}

export function ResponseResultMapStringStringToJSONTyped(value?: ResponseResultMapStringString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': value['data'],
    };
}

