/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 通用响应结果
 * @export
 * @interface ResponseResultLong
 */
export interface ResponseResultLong {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultLong
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultLong
     */
    msg?: string;
    /**
     * 响应数据
     * @type {number}
     * @memberof ResponseResultLong
     */
    data?: number;
}

/**
 * Check if a given object implements the ResponseResultLong interface.
 */
export function instanceOfResponseResultLong(value: object): value is ResponseResultLong {
    return true;
}

export function ResponseResultLongFromJSON(json: any): ResponseResultLong {
    return ResponseResultLongFromJSONTyped(json, false);
}

export function ResponseResultLongFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultLong {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ResponseResultLongToJSON(json: any): ResponseResultLong {
    return ResponseResultLongToJSONTyped(json, false);
}

export function ResponseResultLongToJSONTyped(value?: ResponseResultLong | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': value['data'],
    };
}

