/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MedicationReminderVo } from './MedicationReminderVo';
import {
    MedicationReminderVoFromJSON,
    MedicationReminderVoFromJSONTyped,
    MedicationReminderVoToJSON,
    MedicationReminderVoToJSONTyped,
} from './MedicationReminderVo';

/**
 * 通用响应结果
 * @export
 * @interface ResponseResultListMedicationReminderVo
 */
export interface ResponseResultListMedicationReminderVo {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultListMedicationReminderVo
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultListMedicationReminderVo
     */
    msg?: string;
    /**
     * 响应数据
     * @type {Array<MedicationReminderVo>}
     * @memberof ResponseResultListMedicationReminderVo
     */
    data?: Array<MedicationReminderVo>;
}

/**
 * Check if a given object implements the ResponseResultListMedicationReminderVo interface.
 */
export function instanceOfResponseResultListMedicationReminderVo(value: object): value is ResponseResultListMedicationReminderVo {
    return true;
}

export function ResponseResultListMedicationReminderVoFromJSON(json: any): ResponseResultListMedicationReminderVo {
    return ResponseResultListMedicationReminderVoFromJSONTyped(json, false);
}

export function ResponseResultListMedicationReminderVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultListMedicationReminderVo {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MedicationReminderVoFromJSON)),
    };
}

export function ResponseResultListMedicationReminderVoToJSON(json: any): ResponseResultListMedicationReminderVo {
    return ResponseResultListMedicationReminderVoToJSONTyped(json, false);
}

export function ResponseResultListMedicationReminderVoToJSONTyped(value?: ResponseResultListMedicationReminderVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MedicationReminderVoToJSON)),
    };
}

