/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BiometricRecordVo } from './BiometricRecordVo';
import {
    BiometricRecordVoFromJSON,
    BiometricRecordVoFromJSONTyped,
    BiometricRecordVoToJSON,
    BiometricRecordVoToJSONTyped,
} from './BiometricRecordVo';

/**
 * 通用响应结果
 * @export
 * @interface ResponseResultBiometricRecordVo
 */
export interface ResponseResultBiometricRecordVo {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultBiometricRecordVo
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultBiometricRecordVo
     */
    msg?: string;
    /**
     * 
     * @type {BiometricRecordVo}
     * @memberof ResponseResultBiometricRecordVo
     */
    data?: BiometricRecordVo;
}

/**
 * Check if a given object implements the ResponseResultBiometricRecordVo interface.
 */
export function instanceOfResponseResultBiometricRecordVo(value: object): value is ResponseResultBiometricRecordVo {
    return true;
}

export function ResponseResultBiometricRecordVoFromJSON(json: any): ResponseResultBiometricRecordVo {
    return ResponseResultBiometricRecordVoFromJSONTyped(json, false);
}

export function ResponseResultBiometricRecordVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultBiometricRecordVo {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : BiometricRecordVoFromJSON(json['data']),
    };
}

export function ResponseResultBiometricRecordVoToJSON(json: any): ResponseResultBiometricRecordVo {
    return ResponseResultBiometricRecordVoToJSONTyped(json, false);
}

export function ResponseResultBiometricRecordVoToJSONTyped(value?: ResponseResultBiometricRecordVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': BiometricRecordVoToJSON(value['data']),
    };
}

