/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BiometricRecord } from './BiometricRecord';
import {
    BiometricRecordFromJSON,
    BiometricRecordFromJSONTyped,
    BiometricRecordToJSON,
    BiometricRecordToJSONTyped,
} from './BiometricRecord';

/**
 * 通用响应结果
 * @export
 * @interface ResponseResultBiometricRecord
 */
export interface ResponseResultBiometricRecord {
    /**
     * 状态码
     * @type {number}
     * @memberof ResponseResultBiometricRecord
     */
    code?: number;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseResultBiometricRecord
     */
    msg?: string;
    /**
     * 
     * @type {BiometricRecord}
     * @memberof ResponseResultBiometricRecord
     */
    data?: BiometricRecord;
}

/**
 * Check if a given object implements the ResponseResultBiometricRecord interface.
 */
export function instanceOfResponseResultBiometricRecord(value: object): value is ResponseResultBiometricRecord {
    return true;
}

export function ResponseResultBiometricRecordFromJSON(json: any): ResponseResultBiometricRecord {
    return ResponseResultBiometricRecordFromJSONTyped(json, false);
}

export function ResponseResultBiometricRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseResultBiometricRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : BiometricRecordFromJSON(json['data']),
    };
}

export function ResponseResultBiometricRecordToJSON(json: any): ResponseResultBiometricRecord {
    return ResponseResultBiometricRecordToJSONTyped(json, false);
}

export function ResponseResultBiometricRecordToJSONTyped(value?: ResponseResultBiometricRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': BiometricRecordToJSON(value['data']),
    };
}

