/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SleepLog
 */
export interface SleepLog {
    /**
     * 
     * @type {number}
     * @memberof SleepLog
     */
    logId?: number;
    /**
     * 
     * @type {number}
     * @memberof SleepLog
     */
    accountId?: number;
    /**
     * 
     * @type {Date}
     * @memberof SleepLog
     */
    sleepStart?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SleepLog
     */
    sleepEnd?: Date;
    /**
     * 
     * @type {number}
     * @memberof SleepLog
     */
    sleepQuality?: number;
    /**
     * 
     * @type {Date}
     * @memberof SleepLog
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the SleepLog interface.
 */
export function instanceOfSleepLog(value: object): value is SleepLog {
    return true;
}

export function SleepLogFromJSON(json: any): SleepLog {
    return SleepLogFromJSONTyped(json, false);
}

export function SleepLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): SleepLog {
    if (json == null) {
        return json;
    }
    return {
        
        'logId': json['logId'] == null ? undefined : json['logId'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'sleepStart': json['sleepStart'] == null ? undefined : (new Date(json['sleepStart'])),
        'sleepEnd': json['sleepEnd'] == null ? undefined : (new Date(json['sleepEnd'])),
        'sleepQuality': json['sleepQuality'] == null ? undefined : json['sleepQuality'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function SleepLogToJSON(json: any): SleepLog {
    return SleepLogToJSONTyped(json, false);
}

export function SleepLogToJSONTyped(value?: SleepLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logId': value['logId'],
        'accountId': value['accountId'],
        'sleepStart': value['sleepStart'] == null ? undefined : ((value['sleepStart']).toISOString()),
        'sleepEnd': value['sleepEnd'] == null ? undefined : ((value['sleepEnd']).toISOString()),
        'sleepQuality': value['sleepQuality'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

