/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 睡眠记录请求参数
 * @export
 * @interface SleepLogDto
 */
export interface SleepLogDto {
  /**
   * 入睡时间（时间戳格式）
   * @type {Date}
   * @memberof SleepLogDto
   */
  sleepStart: Date;
  /**
   * 醒来时间（时间戳格式）
   * @type {Date}
   * @memberof SleepLogDto
   */
  sleepEnd: Date;
  /**
   * 睡眠质量（1-5级）
   * @type {number}
   * @memberof SleepLogDto
   */
  sleepQuality?: number;
}

/**
 * Check if a given object implements the SleepLogDto interface.
 */
export function instanceOfSleepLogDto(value: object): value is SleepLogDto {
  if (!('sleepStart' in value) || value['sleepStart'] === undefined) return false;
  if (!('sleepEnd' in value) || value['sleepEnd'] === undefined) return false;
  return true;
}

export function SleepLogDtoFromJSON(json: any): SleepLogDto {
  return SleepLogDtoFromJSONTyped(json, false);
}

export function SleepLogDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SleepLogDto {
  if (json == null) {
    return json;
  }
  return {

    'sleepStart': (new Date(json['sleepStart'])),
    'sleepEnd': (new Date(json['sleepEnd'])),
    'sleepQuality': json['sleepQuality'] == null ? undefined : json['sleepQuality'],
  };
}

export function SleepLogDtoToJSON(json: any): SleepLogDto {
  return SleepLogDtoToJSONTyped(json, false);
}

export function SleepLogDtoToJSONTyped(value?: SleepLogDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'sleepStart': ((value['sleepStart']).toISOString()),
    'sleepEnd': ((value['sleepEnd']).toISOString()),
    'sleepQuality': value['sleepQuality'],
  };
}

