/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInfoVo
 */
export interface UserInfoVo {
    /**
     * 
     * @type {number}
     * @memberof UserInfoVo
     */
    accountId?: number;
    /**
     * 
     * @type {string}
     * @memberof UserInfoVo
     */
    username?: string;
    /**
     * 
     * @type {number}
     * @memberof UserInfoVo
     */
    accountType?: number;
    /**
     * 
     * @type {string}
     * @memberof UserInfoVo
     */
    birthday?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfoVo
     */
    email?: string;
}

/**
 * Check if a given object implements the UserInfoVo interface.
 */
export function instanceOfUserInfoVo(value: object): value is UserInfoVo {
    return true;
}

export function UserInfoVoFromJSON(json: any): UserInfoVo {
    return UserInfoVoFromJSONTyped(json, false);
}

export function UserInfoVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfoVo {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'username': json['username'] == null ? undefined : json['username'],
        'accountType': json['accountType'] == null ? undefined : json['accountType'],
        'birthday': json['birthday'] == null ? undefined : json['birthday'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function UserInfoVoToJSON(json: any): UserInfoVo {
    return UserInfoVoToJSONTyped(json, false);
}

export function UserInfoVoToJSONTyped(value?: UserInfoVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'username': value['username'],
        'accountType': value['accountType'],
        'birthday': value['birthday'],
        'email': value['email'],
    };
}

