/* tslint:disable */
/* eslint-disable */
/**
 * TTXX健康
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserInfoDto
 */
export interface UserInfoDto {
  /**
   *
   * @type {string}
   * @memberof UserInfoDto
   */
  birthday?: string;
}

/**
 * Check if a given object implements the UserInfoDto interface.
 */
export function instanceOfUserInfoDto(value: object): value is UserInfoDto {
  return true;
}

export function UserInfoDtoFromJSON(json: any): UserInfoDto {
  return UserInfoDtoFromJSONTyped(json, false);
}

export function UserInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfoDto {
  if (json == null) {
    return json;
  }
  return {

    'birthday': json['birthday'] == null ? undefined : json['birthday'],
  };
}

export function UserInfoDtoToJSON(json: any): UserInfoDto {
  return UserInfoDtoToJSONTyped(json, false);
}

export function UserInfoDtoToJSONTyped(value?: UserInfoDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'birthday': value['birthday'],
  };
}

